Fix compile error on Windows
webserver.cpp(171): error C4996: 'open': The POSIX name for this item
is deprecated. Instead, use the ISO C and C++ conformant name: _open.
See online help for details.